Numpy : Practice Problem

In [1]:
import numpy as np

1. Extract all odd numbers from arr


In [3]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==0]

array([0, 2, 4, 6, 8])

2. Replace all odd numbers in arr with -1

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

3. Convert a 1D array to a 2D array with 2 rows

In [6]:
arr=np.arange(10)
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

4. Stack arrays a and b vertically

In [12]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

5. Get all items between 5 and 10 from a

In [18]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>=5)&(a<=10)]

array([ 6,  9, 10])

Desired Output:
(array([6, 9, 10]),)

6. Create a null vector of size 10 but the fifth value which is 1.

In [22]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49.

In [23]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

8. Create a 10x10 array with random values and find the minimum and maximum values.

In [25]:
a=np.random.randn(100).reshape(10,10)
a

array([[-0.02010047, -0.06490973,  0.37009601,  0.33110657,  0.46868584,
        -0.6005698 , -0.00724918, -0.58552109, -1.34009664, -1.32107856],
       [ 0.47494208, -0.07418926, -1.18104765, -0.31165642, -0.82397753,
        -0.25956069, -1.01518215,  0.2222494 ,  1.25879272, -2.42527126],
       [ 1.88290519, -0.53953394,  0.12049434, -1.67116062, -0.48355193,
         0.07464282, -1.32641958, -0.44101893,  1.32642047,  0.05347619],
       [ 0.89304277, -0.30188745, -1.49576422, -2.16961821,  1.10160988,
         0.48314081, -1.18539247, -0.28156715, -1.07167436,  1.37887019],
       [-0.77087068, -0.31623947, -0.74758793, -0.12985029,  0.32418877,
         0.59282028,  0.28745664,  0.16924308,  2.07595056,  0.70279171],
       [ 0.42382429, -0.4659101 , -0.17684536, -1.37343931, -0.36317508,
         0.74128171,  0.8021447 ,  2.27090554, -0.83536771,  0.88799503],
       [-0.56590482, -2.8303821 ,  0.53020296, -0.21306863, -1.01717039,
         0.23111423, -0.85521214, -1.01255477

9. Create a 3*3 matrix and print it's transpose matrix

In [28]:
np.arange(9).reshape(3,3).T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

10. Create two arrays of 2-D and find dot product of it.

In [30]:
a=np.arange(6)
b=np.arange(6,12)
np.dot(a,b)

145

11. Compute the maximum for each row in the given array.

In [35]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
np.amax(a,axis=1)
# a

array([9, 8, 6, 3, 9])

12. Select 3rd & 5th row and 3rd & 4th columns

In [42]:
data = np.random.randint(10,100,(5,4))
data[2:4,2:3]
data

array([[49, 61, 40, 76],
       [34, 65, 27, 55],
       [99, 55, 45, 26],
       [22, 96, 92, 77],
       [30, 20, 18, 99]])

In [44]:
data[2:4,2:]


array([[45, 26],
       [92, 77]])

13. Convert below matrix into vector

In [45]:
matrix = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

14. The product of two inverse matrix is identical matrix,prove

In [50]:
# create a square matrix
m = np.array([[2,3],
              [2,4]])
n = np.linalg.inv(m)
np.array(np.dot(m,n), dtype=int)


array([[1, 0],
       [0, 1]])

15. Create a matrix from a uniform distribution over [0, 1)


In [48]:
np.random.uniform(0,1,(2,2))

array([[0.36074842, 0.88001849],
       [0.27454204, 0.22458118]])